#!/bin/sh

if [ -f "/provisioning-configs/proxy.env" ]; then
	echo "The default-proxy bootstrap token already exists. [SKIP]"
	exit 0
fi

echo "# Automatically generated by reverse-proxy-provisioner" >> /provisioning-configs/proxy.env

# Register the default-proxy bootstrap token with the Netbird server
echo "Registering the default-proxy bootstrap token with the Netbird server..."
NB_PROXY_TOKEN=$(docker compose exec -T netbird-server /go/bin/netbird-server admin token create --name "default-proxy" --config /etc/netbird/config.yaml 2>/dev/null | grep "^Token:" | awk '{print $2}')
if [ -z "$NB_PROXY_TOKEN" ]; then
	echo "ERROR: Failed to create proxy token. Check netbird-server logs." > /dev/stderr
	docker compose logs --tail=20 netbird-server
	exit 1
fi
echo "The default-proxy bootstrap token has been created successfully."
echo ""
echo "export NB_PROXY_TOKEN=$NB_PROXY_TOKEN" >> /provisioning-configs/proxy.env

# Register CrowdSec bouncer if NB_PROXY_CROWDSEC_API_URL is set
if [[ -n "${NB_PROXY_CROWDSEC_API_URL}" ]]; then
	echo "Registering CrowdSec bouncer..."
	while ! docker compose exec -T crowdsec cscli lapi status >/dev/null 2>&1; do
		echo "Waiting for CrowdSec to be ready..."
		sleep 2
	done
	NB_PROXY_CROWDSEC_API_KEY=$(docker compose exec -T crowdsec cscli bouncers add netbird-proxy -o raw 2>/dev/null)
	if [[ -z "$NB_PROXY_CROWDSEC_API_KEY" ]]; then
		echo "WARNING: Failed to create CrowdSec bouncer key. Exiting." > /dev/stderr
		exit 1
	else
		echo "CrowdSec bouncer registered."
	fi
	echo "export NB_PROXY_CROWDSEC_API_KEY=$NB_PROXY_CROWDSEC_API_KEY" >> /provisioning-configs/proxy.env
	echo ""
fi

echo "Provisioning completed successfully."
echo "The provisioning configuration has been saved to /provisioning-configs/proxy.env"
echo ""
echo "Provisioning configuration:"
cat /provisioning-configs/proxy.env | grep -v '^#' | sed 's/^export //'
